from eegnb.devices.utils import (  # noqa: F401
    CYTON_CONFIG_GAIN_1X,
    CYTON_CONFIG_GAIN_2X,
    CYTON_CONFIG_GAIN_4X,
    CYTON_CONFIG_GAIN_6X,
    CYTON_CONFIG_GAIN_12X,
    CYTON_CONFIG_GAIN_24X,
)
